services:
  - type: web
    name: crypto-app
    env: node
    buildCommand: "npm install"
    startCommand: "node index.js" # Or your entry file
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # Update it in the Render Dashboard
